on:
  push:
jobs:
  test:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "Prepare Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: "Lint"
        run: |
          make lint

      - name: "Test"
        run: |
          make test-coverage

  publish:
    runs-on: "ubuntu-latest"
    needs: "test"
    if: "startsWith(github.ref, 'refs/tags/v')"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "Publish to Pypi"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
          repository-url: "https://test.pypi.org/legacy/"

      # - name: "Create Release"
      #   uses: "actions/create-release@v1"
      #   with:
      #     tag_name: "${{ github.ref }}"
      #     release_name: "Release ${{ github.ref }}"